### ISSUE TITLE
I need help, why is happening this? Using COMPUTE_MAXS

### ISSUE THREAD

**Issue by MrAlecroYT** [java-deobfuscator/deobfuscator#369]
C:\Users\mysystem\Documents\Ofuscator>java -Xmx2G -jar deob3.jar --config config.yml
[main] WARN com.javadeobfuscator.deobfuscator.DeobfuscatorMain - The specified output JAR already exists!
[main] WARN com.javadeobfuscator.deobfuscator.DeobfuscatorMain - I was unable to back up the previous output JAR
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.stringer.StringEncryptionTransformer
[Stringer] [StringEncryptionTransformer] Starting
[Stringer] [StringEncryptionTransformer] Found 0 encrypted strings
[Stringer] [StringEncryptionTransformer] Done
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing
Error: java/lang/Exception could not be found while writing me/wazup/skywars/Arena. Using COMPUTE_MAXS
Error: java/sql/Connection could not be found while writing me/wazup/skywars/PlayerData. Using COMPUTE_MAXS
Error: java/sql/PreparedStatement could not be found while writing me/wazup/skywars/SkywarsAPI. Using COMPUTE_MAXS
Error: org/bukkit/Location could not be found while writing me/wazup/skywars/Arena$TeamData. Using COMPUTE_MAXS
Error: java/sql/Connection could not be found while writing me/wazup/skywars/PlayerData$1. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing me/wazup/skywars/Config. Using COMPUTE_MAXS
Error: java/lang/Object could not be found while writing me/wazup/skywars/SkywarsListener. Using COMPUTE_MAXS
Error: java/sql/PreparedStatement could not be found while writing me/wazup/skywars/Skywars$4. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing me/wazup/skywars/Skywars. Using COMPUTE_MAXS
Error: java/lang/String could not be found while writing me/wazup/skywars/Skywars$14. Using COMPUTE_MAXS
Error: java/util/List could not be found while writing me/wazup/skywars/ItemStackBuilder. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing me/wazup/skywars/Skywars$16. Using COMPUTE_MAXS
Error: java/io/IOException could not be found while writing me/wazup/skywars/Skywars$17. Using COMPUTE_MAXS
Error: java/util/Iterator could not be found while writing me/wazup/skywars/Skywars$19. Using COMPUTE_MAXS

My Config.yml
```input: skywars.jar
output: skywars0f.jar
path:
 - path/C:\path\C:\Program Files\Java\jre1.8.0_201\lib/rt.jar
 - path/C:\path\C:\Users\mysystem\Documents\Ofuscator/HolographicDisplaysAPI.jar 
 - path/C:\path\C:\Users\mysystem\Documents\Ofuscator/MVdWPlaceholderAPI.jar
 - path/C:\path\C:\Users\mysystem\Documents\Ofuscator/PlaceholderAPI-2.8.2.jar
 - path/C:\path\C:\Users\mysystem\Documents\Ofuscator/TitleManager.jar 
 - path/C:\path\C:\Users\mysystem\Documents\Ofuscator/Vault.jar
 - path/C:\path\C:\Users\mysystem\Documents\Ofuscator/spigot.jar
transformers:
 - stringer.StringEncryptionTransformer```


I need help please.

**Comment by Janmm14** [comment]
Please use three ` at start and end of the config file so it's marked as raw code.

It looks like you did not correctly specified the path entries, the deobfuscator did not found classes which are in rt.jar

**Comment by MrAlecroYT** [comment]
I mean what I need to do to fix the problem?

**Comment by ItzSomebody** [comment]
```yaml
output: skywars0f.jar
path:
 - "C:\\Program Files\\Java\\jre1.8.0_201\\lib\\rt.jar"
 - "C:\\Users\\mysystem\\Documents\\Ofuscator\\HolographicDisplaysAPI.jar"
 - "C:\\Users\\mysystem\\Documents\\Ofuscator\\MVdWPlaceholderAPI.jar"
 - "C:\\Users\\mysystem\\Documents\\Ofuscator\\PlaceholderAPI-2.8.2.jar"
 - "C:\\Users\\mysystem\\Documents\\Ofuscator\\TitleManager.jar"
 - "C:\\Users\\mysystem\\Documents\\Ofuscator\\Vault.jar"
 - "C:\\Users\\mysystem\\Documents\\Ofuscator\\spigot.jar"
transformers:
 - stringer.StringEncryptionTransformer
```
