### ISSUE TITLE
Should be stringer but it doesn't work

### ISSUE THREAD

**Issue by fahrenheit93** [java-deobfuscator/deobfuscator#385]
Hey there, i'm trying to deobfuscate a mod from minecraft, using Stringer i think : 
From MANIFEST.MF :
```
Manifest-Version: 1.0
Protected-Notice: AV contact email - primary@licelus.com
JAR-Signature: tKCW76f9jnpfD+oSTkqAoBqXx6RkpcVqzZ1Ay6nJb0/XESUo
Protected-By: 3.1.3 Stringer (20170802)
```

My config.yml :
```YAML
input: Minecraft-mod.jar
output: Minecraft-mod-DeobTest.jar
transformers:
  - stringer.StringEncryptionTransformer
```

The detect.yml :
![image](https://user-images.githubusercontent.com/48847643/54860596-c4f00c80-4d1c-11e9-827b-4617ddc342e8.png)

Can you help me? Should be great !

Another question, where is the full list of transformers (like "normalizer.SourceFileClassNormalizer" for example) thank you.
[Mod Minecraft.zip](https://github.com/java-deobfuscator/deobfuscator/files/2998934/palamod.zip)
