### ISSUE TITLE
[NoSuchMethodHandlerException] Hide Access Transformer

### ISSUE THREAD

**Issue by fahrenheit93** [java-deobfuscator/deobfuscator#387]
Hello again, i'm opening a new issue because the last one was resolved for the first of two files.
The second one :  [palamodaddons-1.0.0.jar.zip](https://github.com/java-deobfuscator/deobfuscator/files/3024994/palamodaddons-1.0.0.jar.zip)

I logged the different classes here : 
```JAVA
classNodes().forEach(classNode ->
    classNode.methods.stream().filter(methodNode -> !methodNode.desc.equals(bootstrapDesc)).forEach(methodNode -> {
            if (DEV) {
                System.out.println("ClassNode Name : " + classNode.name);
                System.out.println("ClassNode File : " + classNode.sourceFile);
            }
```
From here, i ignore the class causing the NullException, i don't know if it's good or not.

My config file :

```YAML
input: "C:\\Users\\moi\\Documents\\re\\palamod\\fork\\palamodaddons-string.jar"
output: "C:\\Users\\moi\\Documents\\re\\palamod\\fork\\palamodaddons-1.0.0-deob-debug.jar"
path:
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\bootstrap\\runtime\\jre-x64-1.8.0_25-windows\\lib\\rt.jar"
ignoredClasses:
  - palamodaddons/modules/paladium/items/armors/BaseItemArmorEffect
  - palamodaddons/modules/paladium/items/tools/BaseItemAxe
  - palamodaddons/modules/paladium/items/tools/BaseItemShovel
  - palamodaddons/modules/paladium/PPaladium
  - palamodaddons/modules/paladium/items/weapons/BaseItemSword
  - palamodaddons/modules/paladium/materials/PArmorMaterial
  - palamodaddons/modules/paladium/items/armors/ItemRepairableArmor
  - palamodaddons/modules/paladium/items/weapons/ItemPaladiumGreenSword
  - palamodaddons/modules/paladium/items/armors/BaseItemArmor
  - palamodaddons/modules/paladium/materials/PToolMaterial
  - palamodaddons/modules/paladium/items/tools/BaseItemPickaxe
  - palamodaddons/common/creativetab/PCreativeTab
  - palamodaddons/client/gui/PGuiOverlayDebugOld
  - palamodaddons/client/gui/PGuiOverlayDebug
  - palamodaddons/kiwi/Kiwi
  - palamodaddons/client/gui/PGuiIngame
  - palamodaddons/utils/Utils
  - palamodaddons/kiwi/MKiwiConnect
  - palamodaddons/client/events/yv
  - palamodaddons/client/events/GuiHandler
  - palamodaddons/kiwi/MKiwiLoader
  - palamodaddons/pulsar/pulse/Pulse
  - palamodaddons/client/on
libraries:
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\libraries\\net\\minecraftforge\\forge\\1.7.10-10.13.4.2512\\forge-1.7.10-10.13.4.2512.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\libraries\\com\\google\\guava\\guava\\17.0\\guava-17.0.jar"
  - "C:\\Users\\moi\\Documents\\re\\minecraft.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\libraries\\io\\netty\\netty-all\\4.0.10.Final\\netty-all-4.0.10.Final.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\libraries\\com\\mojang\\authlib\\1.5.21\\authlib-1.5.21.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.0-beta9\\log4j-api-2.0-beta9.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\libraries\\net\\minecraft\\launchwrapper\\1.12\\launchwrapper-1.12.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\ArmorStatusHUD.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\BiblioCraft.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\Chisel.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\CodeChickenCore.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\CustomNPCs.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\Discord.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\IronChest.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\json-simple-1.1.1.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\NotEnoughItems.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\Optifine.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\PalaChristmasDeco-Client.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\Paladium-CEF.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\palamodaddons-1.0.0.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\RandomThings.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\RTG.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\SecretRooms.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\StatusEffectHUD.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\StorageDrawers.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\1.7.10\\[1.7.10]bspkrsCore-universal-6.15.jar"
  - "C:\\Users\\moi\\AppData\\Roaming\\.paladium\\minecraft\\mods\\1.7.10\\CodeChickenLib-1.7.10-1.1.1.99-universal.jar"
  - "C:\\Users\\moi\\Documents\\re\\Palamod-Client.jar"
  - "C:\\Users\\moi\\Documents\\re\\commons-io-2.6.jar"
transformers:
  - stringer.HideAccessObfuscationTransformer
```

The error : 
`com.javadeobfuscator.deobfuscator.executor.exceptions.NoSuchMethodHandlerException: Could not find invoker for palamodaddons/client/on R(I)Ljava/lang/reflect/Method; @ palamodaddons/client/PProxyClient vT(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
at com.javadeobfuscator.deobfuscator.executor.MethodExecutor.execute(MethodExecutor.java:1359)`

It says couldn't find, yes i ignored these ones, if not, it's NullPointerException...

I used StringEncryptionTransformer one time before and it worked.
I tried with doing a ClassNormalizer too.
I tried doing a ReflectionObfuscationTransformer but `java.lang.ArrayIndexOutOfBoundsException
at java.lang.reflect.Array.get(Native Method)
` so..

I you can do it, please tell me how you did it thank you.

P.S : I don't want to ignore so much files, that's useless..
