### ISSUE TITLE
Help with understanding how this program work

### ISSUE THREAD

**Issue by iGabyTM** [java-deobfuscator/deobfuscator#639]
I have tried to deobfuscate a jar file for testing and I can't figure out how to add the libraries used. This is my config:
```yml
input: in.jar
output: out.jar
path:
  - D:/Program Files/Java/jdk8u242-b08-jre/lib/rt.jar
  - D:/Projects/MinecraftServers/test/server.jar
libraries:
  - D:/Projects/MinecraftServers/test/server.jar
transformers:
  - normalizer.SourceFileClassNormalizer
  - normalizer.MethodNormalizer: {}
```
```sql
Could not locate a class file.
Have you added the necessary files to the -path argument?
The error was:
com.javadeobfuscator.deobfuscator.exceptions.NoClassInPathException: org/bukkit/event/Listener
```

Also, I noticed that `MethodNormalizer` require a value named `mapping-file`, how do I generate one?
