### ISSUE TITLE
Dependency trouble with deobfuscator and native Java libraries

### ISSUE THREAD

**Issue by brownbananas95** [java-deobfuscator/deobfuscator#666]
I am having some trouble with paths and libraries when deobfuscating. 

Current java version:
```console
$ java --version
openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
```

config.yml
```yaml
input: input.jar
output: output.jar
path:
  - /home/user/deobfuscator/good/client-1.6.33-SNAPSHOT-shaded.jar
    # - /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
    # - /usr/lib/jvm/java-8-openjdk-amd64/lib/jce.jar
    #- /usr/lib/jvm/java-8-openjdk-amd64/lib/jsse.jar
libraries:
  - /home/user/deobfuscator/good/client-1.6.33-SNAPSHOT-shaded.jar
    # - /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
    # - /usr/lib/jvm/java-8-openjdk-amd64/lib/jce.jar
    # - /usr/lib/jvm/java-8-openjdk-amd64/lib/jsse.jar
transformers:
  - com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer
  - com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer
  - com.javadeobfuscator.deobfuscator.transformers.zelix.FlowObfuscationTransformer
  - com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalSignatureRemover
  - com.javadeobfuscator.deobfuscator.transformers.general.removers.IllegalVarargsRemover
  - com.javadeobfuscator.deobfuscator.transformers.general.removers.LineNumberRemover
  - com.javadeobfuscator.deobfuscator.transformers.general.removers.LocalVariableRemover
  - com.javadeobfuscator.deobfuscator.transformers.general.removers.SyntheticBridgeRemover
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.ClassNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.EnumNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.FieldNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.MethodNormalizer
  - com.javadeobfuscator.deobfuscator.transformers.normalizer.SourceFileClassNormalizer
```

When attempting to deobfuscate I get errors related to Javas default library... I thought this would be imported implicitly when using Java in the first place?

```console
$ java -jar deobfuscator.jar --config config.yml
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer
[Zelix] [StringEncryptionTransformer] Starting
[Zelix] [StringEncryptionTransformer] Decrypted strings from 19 encrypted classes
[Zelix] [StringEncryptionTransformer] Decrypted 542 strings
[Zelix] [StringEncryptionTransformer] Done
[main] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Running com.javadeobfuscator.deobfuscator.transformers.zelix.ReflectionObfuscationTransformer
[Zelix] [ReflectionObfuscationTransformer] Starting
[Zelix] [ReflectionObfuscationTransformer] Finding reflection obfuscation
[Zelix] [ReflectionObfuscationTransformer] Found 7 reflection obfuscation instructions
Could not find classnode java.lang.String


** DO NOT OPEN AN ISSUE ON GITHUB ** <--- Sorry, but I am having trouble figuring this out without doing it :\ 
Could not locate a class file.
Have you added the necessary files to the -path argument?
The error was:
com.javadeobfuscator.deobfuscator.exceptions.NoClassInPathException: java.lang.String
	at com.javadeobfuscator.deobfuscator.executor.defined.types.JavaClass.<init>(JavaClass.java:61)
```
The `input.jar` and the dependency `client-1.6.33-SNAPSHOT-shaded.jar` are also built with JDK 11.

If I import jars from JDK 8 as seen in `config.yml` I manage to get past the error, but since these files are compiled with JDK 11 I get a new error `Error: java/net/http/HttpClient could not be found while writing net/runelite/client/plugins/PluginX/PluginX. Using COMPUTE_MAXS` which highly likely is because of the JDK 8 imports which solve the `java.lang.String` classnode error, causing a version mixup. I have therefore removed the JDK 8 jars from `config.yml`.

I have confirmed that `java.lang.String` is officially used in JDK 11, and find it weird if native Java libraries would have to be imported when deobfuscator itself is invoked with Java. Is this the case and its just me missing something obvious here? If so, how is that done correctly?

Possibly related answer [#217](https://github.com/java-deobfuscator/deobfuscator/issues/217#issuecomment-372051213).
