### ISSUE TITLE
Issue with DashO deobfuscation

### ISSUE THREAD

**Issue by InfiniteAura** [java-deobfuscator/deobfuscator#874]
I am currently having some trouble with the DashO StringEncryptionTransformer. Everything seems to go fine until the deobfuscator tries to write to the output jar and it gives me this "Failed to compute frames" error.
Here's the config I used:
```yaml
input: REDACTED.jar
output: out.jar
detect: false
path:
 - C:\Users\infAura\Desktop\javax-crypto.jar
 - D:\coding\Depends\ProtocolLib.jar
 - D:\coding\Depends\spigot-1.7.10-SNAPSHOT-b1657.jar
 - D:\coding\Depends\spigot-1.8.8-R0.1-SNAPSHOT-latest.jar
 - C:\Program Files\Java\jre1.8.0_321\lib\rt.jar
transformers:
 - dasho.FakeExceptionTransformer
 - dasho.FlowObfuscationTransformer
 - dasho.StringEncryptionTransformer
```
